server:
  port: 7778
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: com
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3308/smart?useUnicode=true&characterEncoding=UTF-8
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 10
      stat-view-servlet:
        login-password: druid
        login-username: druid
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      password: 123456
      username: root
  redis:
    database: 0
    host: 127.0.0.1
    password: ''
    port: 6379
    timeout: 300
  swagger-enable: true  #swagger 开关
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: lwq
    password: 123
    publisher-confirms: true
    # exclusive
    virtual-host:



smart:
  password: 202cb962ac59075b964b07152d234b70
  excetion:
    enable: true  #是否显示异常


logging:
  level:
    com:
      smart:
        db:
          dao: debug

